version: '3'

volumes:
  cache: # win10 docker support

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/app
    ports:
      - 3000:3000 # # response test script
      - 4100:8080 #
      - 4101:8081
      - 5683:5683/udp # coap app
    command: python response_test.py # tail -F anything # python run_server.py # bash


  db:
    image: mysql:8.0.16
    ports:
      - 4001:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1324
      MYSQL_DATABASE: db
      MYSQL_USER: backend
      MYSQL_PASSWORD: 1234
